version: '3.8'

services:
  frontend:
    image: ayush272002/fightlinx-frontend:latest
    environment:
      - NEXT_PUBLIC_API_BASE_URL=http://localhost:8000
    ports:
      - '3000:3000'

  backend:
    image: ayush272002/fightlinx-backend:latest
    environment:
      - PORT=8000
      - JWT_SECRET=secret
      - DATABASE_URL=postgresql://postgres:postgres@postgres:5432/fightlinx
      - ALLOWED_ORIGINS=http://frontend:3000
      - KAFKA_URI=kafka:9092
    ports:
      - '8000:8000'

  mm:
    image: ayush272002/fightlinx-mm:latest
    environment:
      - PORT=8000
      - DATABASE_URL=postgresql://postgres:postgres@postgres:5432/fightlinx
      - KAFKA_URI=kafka:9092

  postgres:
    image: postgres:latest
    environment:
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=postgres
      - POSTGRES_DB=fightlinx
    ports:
      - '5432:5432'

  redis:
    image: redis:latest
    ports:
      - '6379:6379'

  kafka:
    image: apache/kafka:latest
    ports:
      - '9092:9092'
