version: '3.8'

services:
  backend:
    image: ayush272002/fightlinx-backend:latest
    environment:
      - PORT=8000
      - JWT_SECRET=secret
      - DATABASE_URL=
      - ALLOWED_ORIGINS=http://localhost:3000
      - KAFKA_URI=
      - KAFKA_USERNAME=
      - KAFKA_PASSWORD=
      - REDIS_URL=
    ports:
      - '8000:8000'

  mm:
    image: ayush272002/fightlinx-mm:latest
    environment:
      - DATABASE_URL=
      - KAFKA_URI=
      - KAFKA_USERNAME=
      - KAFKA_PASSWORD=
      - REDIS_URL=