name: Build, Deploy, and Verify Docker Images

on:
  push:
    branches:
      - main

jobs:
  build-deploy-verify:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3

      - name: Log in to Docker Hub
        uses: docker/login-action@v3
        with:
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_PASSWORD }}

      - name: Build and push frontend image
        run: |
          docker build -f docker/Dockerfile.frontend -t ayush272002/fightlinx-frontend:latest .
          docker push ayush272002/fightlinx-frontend:latest

      - name: Build and push backend image
        run: |
          docker build -f docker/Dockerfile.backend -t ayush272002/fightlinx-backend:latest .
          docker push ayush272002/fightlinx-backend:latest

      - name: Build and push mm image
        run: |
          docker build -f docker/Dockerfile.mm -t ayush272002/fightlinx-mm:latest .
          docker push ayush272002/fightlinx-mm:latest

      - name: Verify frontend image by pulling
        run: |
          docker pull ayush272002/fightlinx-frontend:latest
          docker images | grep ayush272002/fightlinx-frontend

      - name: Verify backend image by pulling
        run: |
          docker pull ayush272002/fightlinx-backend:latest
          docker images | grep ayush272002/fightlinx-backend

      - name: Verify mm image by pulling
        run: |
          docker pull ayush272002/fightlinx-mm:latest
          docker images | grep ayush272002/fightlinx-mm
