name: Build, Deploy, and Verify Docker Images

on:
  push:
    branches:
      - main

jobs:
  build-deploy-verify:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3

      - name: Log in to Docker Hub
        uses: docker/login-action@v3
        with:
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_PASSWORD }}

      - name: Build and push backend image
        run: |
          docker build -f docker/Dockerfile.backend -t ayush272002/fightlinx-backend:latest .
          docker push ayush272002/fightlinx-backend:latest

      - name: Build and push mm image
        run: |
          docker build -f docker/Dockerfile.mm -t ayush272002/fightlinx-mm:latest .
          docker push ayush272002/fightlinx-mm:latest

      - name: Verify backend image by pulling
        run: |
          docker pull ayush272002/fightlinx-backend:latest
          docker images | grep ayush272002/fightlinx-backend

      - name: Verify mm image by pulling
        run: |
          docker pull ayush272002/fightlinx-mm:latest
          docker images | grep ayush272002/fightlinx-mm

      - name: Deploy to AWS EC2
        uses: appleboy/ssh-action@master
        with:
          host: ${{ secrets.SSH_HOST }}
          username: ${{ secrets.SSH_USERNAME }}
          key: ${{ secrets.SSH_KEY }}
          script: |
            sudo docker stop backend || true
            sudo docker rm backend || true
            sudo docker stop mm || true
            sudo docker rm mm || true
            sudo docker system prune -af
            sudo docker volume prune -f
            sudo docker pull ayush272002/fightlinx-backend:latest
            sudo docker pull ayush272002/fightlinx-mm:latest
            sudo docker run -d \
              --name backend \
              -p 8000:8000 \
              -e PORT=8000 \
              -e ALLOWED_ORIGINS="https://fightlinx.vercel.app" \
              -e JWT_SECRET="${{ secrets.JWT_SECRET }}" \
              -e DATABASE_URL="${{ secrets.DATABASE_URL }}" \
              -e KAFKA_URI="${{ secrets.KAFKA_URI }}" \
              -e KAFKA_USERNAME="${{ secrets.KAFKA_USERNAME }}" \
              -e KAFKA_PASSWORD="${{ secrets.KAFKA_PASSWORD }}" \
              -e REDIS_URL="${{ secrets.REDIS_URL }}" \
              ayush272002/fightlinx-backend:latest
            sudo docker run -d \
              --name mm \
              -e DATABASE_URL="${{ secrets.DATABASE_URL }}" \
              -e KAFKA_URI="${{ secrets.KAFKA_URI }}" \
              -e KAFKA_USERNAME="${{ secrets.KAFKA_USERNAME }}" \
              -e KAFKA_PASSWORD="${{ secrets.KAFKA_PASSWORD }}" \
              -e REDIS_URL="${{ secrets.REDIS_URL }}" \
              ayush272002/fightlinx-mm:latest
